export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const SET_API_IS_CALLING_TRUE = 'SET_API_IS_CALLING_TRUE'
export const SET_API_IS_CALLING_FALSE = 'SET_API_IS_CALLING_FALSE'
